-- MySQL Script generated by MySQL Workbench
-- qui 05 out 2023 20:29:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema engsoftware
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema engsoftware
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `engsoftware` DEFAULT CHARACTER SET utf8 ;
USE `engsoftware` ;

-- -----------------------------------------------------
-- Table `engsoftware`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `engsoftware`.`Usuario` (
  `email` VARCHAR(150) NOT NULL,
  `nomeUsuario` VARCHAR(150) NOT NULL,
  `senha` CHAR(88) NOT NULL,
  `tipoUsuario` ENUM('normal', 'especialista', 'admin') DEFAULT 'normal',
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `engsoftware`.`Relatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `engsoftware`.`Relatorio` (
  `idRelatorio` INT NOT NULL,
  `nomeUsuario` VARCHAR(45) NOT NULL,
  `dataEmissao` VARCHAR(45) NOT NULL,
  `acuracia` VARCHAR(45) NOT NULL,
  `urlFoto` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `filial` VARCHAR(45) NOT NULL,
  `silo` VARCHAR(45) NOT NULL,
  `Usuario_email` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idRelatorio`, `Usuario_email`),
  INDEX `fk_Relatorio_Usuario1_idx` (`Usuario_email` ASC) VISIBLE,
  CONSTRAINT `fk_Relatorio_Usuario1`
    FOREIGN KEY (`Usuario_email`)
    REFERENCES `engsoftware`.`Usuario` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `engsoftware`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `engsoftware`.`Cidade` (
  `idcidade` INT NOT NULL,
  `nomeCidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `engsoftware`.`Filial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `engsoftware`.`Filial` (
  `idFilial` INT NOT NULL,
  `nomeFilial` VARCHAR(45) NOT NULL,
  `Cidade_idcidade` INT NOT NULL,
  PRIMARY KEY (`idFilial`, `Cidade_idcidade`),
  INDEX `fk_Filial_Cidade1_idx` (`Cidade_idcidade` ASC) VISIBLE,
  CONSTRAINT `fk_Filial_Cidade1`
    FOREIGN KEY (`Cidade_idcidade`)
    REFERENCES `engsoftware`.`Cidade` (`idcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `engsoftware`.`Silo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `engsoftware`.`Silo` (
  `idSilo` INT NOT NULL,
  `nomeSilo` VARCHAR(45) CHARACTER SET 'armscii8' NOT NULL,
  `Filial_idFilial` INT NOT NULL,
  `Filial_Cidade_idcidade` INT NOT NULL,
  PRIMARY KEY (`idSilo`, `Filial_idFilial`, `Filial_Cidade_idcidade`),
  INDEX `fk_Silo_Filial1_idx` (`Filial_idFilial` ASC, `Filial_Cidade_idcidade` ASC) VISIBLE,
  CONSTRAINT `fk_Silo_Filial1`
    FOREIGN KEY (`Filial_idFilial` , `Filial_Cidade_idcidade`)
    REFERENCES `engsoftware`.`Filial` (`idFilial` , `Cidade_idcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
