version: '3.3'


services:
  # Banco de dados
  database:
    image: mysql:8.2.0
    restart: always
    container_name: engsoftware-database
    environment:
      MYSQL_DATABASE: 'engsoftware'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
        # Para ser acessado de qualquer client MySQL na m치quina host pelo
        # "localhost:3306"
    expose:
      - '3306'
    networks:
      - "engsoftware"
    volumes:
      # Monta o diret칩rio ./database contendo o c칩digo SQL para inicializar o
      # banco de dados. Assim ele ser치 executado quando a imagem do MySQL for
      # inicializada.
        - ./database:/docker-entrypoint-initdb.d

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: always
    container_name: engsoftware-backend
    ports:
      - '8080:8080'
    expose:
      - '8080'
    links:
      - "database"
    networks:
      - "engsoftware"
    depends_on:
      - database

  # Frontend
  frontend:
    build: .
    restart: always
    container_name: engsoftware-frontend
    ports:
      - '3000:3000'
    expose:
      - '3000'
    networks:
      - "engsoftware"
    depends_on:
      - database
      - backend


networks:
  engsoftware:
    driver: bridge
